// <auto-generated />
using System;
using Fitness_Membership_Tracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness_Membership_Tracker.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260102104354_RemovedRedundantPropertyOfMembership")]
    partial class RemovedRedundantPropertyOfMembership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Dimitar.Mihaylov@gmail.com",
                            FirstName = "Dimitar",
                            HireDate = new DateTime(2020, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Mihaylov",
                            LocationId = 1,
                            PhoneNumber = "6895036713",
                            Salary = 1534m
                        },
                        new
                        {
                            Id = 2,
                            Email = "Kristina.Bozhkov@gmail.com",
                            FirstName = "Kristina",
                            HireDate = new DateTime(2020, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Bozhkov",
                            LocationId = 1,
                            PhoneNumber = "5961832521",
                            Salary = 1668m
                        },
                        new
                        {
                            Id = 3,
                            Email = "Georgi.Kolev@gmail.com",
                            FirstName = "Georgi",
                            HireDate = new DateTime(2020, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kolev",
                            LocationId = 1,
                            PhoneNumber = "8364222141",
                            Salary = 1530m
                        },
                        new
                        {
                            Id = 4,
                            Email = "Desislava.Angelov@gmail.com",
                            FirstName = "Desislava",
                            HireDate = new DateTime(2020, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Angelov",
                            LocationId = 2,
                            PhoneNumber = "4543896634",
                            Salary = 1627m
                        },
                        new
                        {
                            Id = 5,
                            Email = "Mihail.Kovachev@gmail.com",
                            FirstName = "Mihail",
                            HireDate = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kovachev",
                            LocationId = 2,
                            PhoneNumber = "7801150338",
                            Salary = 1692m
                        },
                        new
                        {
                            Id = 6,
                            Email = "Dimitar.Todorov@gmail.com",
                            FirstName = "Dimitar",
                            HireDate = new DateTime(2020, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Todorov",
                            LocationId = 2,
                            PhoneNumber = "2128659047",
                            Salary = 1545m
                        },
                        new
                        {
                            Id = 7,
                            Email = "Mihail.Kovachev@gmail.com",
                            FirstName = "Mihail",
                            HireDate = new DateTime(2020, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kovachev",
                            LocationId = 3,
                            PhoneNumber = "5634491252",
                            Salary = 1416m
                        },
                        new
                        {
                            Id = 8,
                            Email = "Georgi.Petrov@gmail.com",
                            FirstName = "Georgi",
                            HireDate = new DateTime(2020, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Petrov",
                            LocationId = 3,
                            PhoneNumber = "7755709734",
                            Salary = 1683m
                        },
                        new
                        {
                            Id = 9,
                            Email = "Petar.Vladimirov@gmail.com",
                            FirstName = "Petar",
                            HireDate = new DateTime(2020, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Vladimirov",
                            LocationId = 3,
                            PhoneNumber = "6859300378",
                            Salary = 1501m
                        },
                        new
                        {
                            Id = 10,
                            Email = "Nikola.Todorov@gmail.com",
                            FirstName = "Nikola",
                            HireDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Todorov",
                            LocationId = 4,
                            PhoneNumber = "8740622847",
                            Salary = 1502m
                        },
                        new
                        {
                            Id = 11,
                            Email = "Nikola.Nikolov@gmail.com",
                            FirstName = "Nikola",
                            HireDate = new DateTime(2020, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nikolov",
                            LocationId = 4,
                            PhoneNumber = "9479855058",
                            Salary = 1642m
                        },
                        new
                        {
                            Id = 12,
                            Email = "Katerina.Kovachev@gmail.com",
                            FirstName = "Katerina",
                            HireDate = new DateTime(2020, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kovachev",
                            LocationId = 4,
                            PhoneNumber = "4198712334",
                            Salary = 1532m
                        });
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "бул. Черни връх 47, Младост, 1303",
                            City = "Sofia",
                            Country = "Bulgaria"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Пирин 12, Люлин, 1324",
                            City = "Sofia",
                            Country = "Bulgaria"
                        },
                        new
                        {
                            Id = 3,
                            Address = "ул. Христо Ботев 23, Център, 1000",
                            City = "Sofia",
                            Country = "Bulgaria"
                        },
                        new
                        {
                            Id = 4,
                            Address = "ул. Васил Левски 45",
                            City = "Sofia",
                            Country = "Bulgaria"
                        });
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.LocationMembership", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "MembershipId");

                    b.HasIndex("MembershipId");

                    b.ToTable("LocationMembership");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Member", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PaymentId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationRegistered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MembershipTierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MembershipTierId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.MembershipTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxSessionsPerMonth")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MembershipTiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 8,
                            MonthlyPrice = 9.99m,
                            Tier = "Basic"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 12,
                            MonthlyPrice = 15.99m,
                            Tier = "Advanced"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 18,
                            MonthlyPrice = 21.99m,
                            Tier = "elite"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 24,
                            MonthlyPrice = 29.99m,
                            Tier = "Ultimate"
                        });
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MemberId");

                    b.HasIndex("MembershipId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Employee", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.LocationMembership", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Location", "Location")
                        .WithMany("LocationMemberships")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", "Membership")
                        .WithMany("LocationMemberships")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Member", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId");

                    b.Navigation("Membership");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.MembershipTier", "MembershipTier")
                        .WithMany()
                        .HasForeignKey("MembershipTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("MembershipTier");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Payment", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.Navigation("Employee");

                    b.Navigation("Member");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Location", b =>
                {
                    b.Navigation("LocationMemberships");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", b =>
                {
                    b.Navigation("LocationMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
