// <auto-generated />
using System;
using Fitness_Membership_Tracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness_Membership_Tracker.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260219124202_ChangeOneToManyBEtweenLocationToMembershipAndMemberToPayment")]
    partial class ChangeOneToManyBEtweenLocationToMembershipAndMemberToPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Dimitar.Kovachev@gmail.com",
                            FirstName = "Dimitar",
                            HireDate = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Kovachev",
                            LocationId = 1,
                            PhoneNumber = "9470480998",
                            Salary = 1594m
                        },
                        new
                        {
                            Id = 2,
                            Email = "Boris.Kovachev@gmail.com",
                            FirstName = "Boris",
                            HireDate = new DateTime(2020, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Kovachev",
                            LocationId = 1,
                            PhoneNumber = "0345476011",
                            Salary = 1494m
                        },
                        new
                        {
                            Id = 3,
                            Email = "Ivan.Zahariev@gmail.com",
                            FirstName = "Ivan",
                            HireDate = new DateTime(2020, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Zahariev",
                            LocationId = 1,
                            PhoneNumber = "1627322926",
                            Salary = 1616m
                        },
                        new
                        {
                            Id = 4,
                            Email = "Hristo.Zahariev@gmail.com",
                            FirstName = "Hristo",
                            HireDate = new DateTime(2020, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Zahariev",
                            LocationId = 2,
                            PhoneNumber = "1148835719",
                            Salary = 1513m
                        },
                        new
                        {
                            Id = 5,
                            Email = "Radoslav.Bozhkov@gmail.com",
                            FirstName = "Radoslav",
                            HireDate = new DateTime(2020, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Bozhkov",
                            LocationId = 2,
                            PhoneNumber = "9233779113",
                            Salary = 1578m
                        },
                        new
                        {
                            Id = 6,
                            Email = "Svetlana.Hristov@gmail.com",
                            FirstName = "Svetlana",
                            HireDate = new DateTime(2020, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Hristov",
                            LocationId = 2,
                            PhoneNumber = "4399341116",
                            Salary = 1634m
                        },
                        new
                        {
                            Id = 7,
                            Email = "Mihail.Kovachev@gmail.com",
                            FirstName = "Mihail",
                            HireDate = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Kovachev",
                            LocationId = 3,
                            PhoneNumber = "0294378533",
                            Salary = 1485m
                        },
                        new
                        {
                            Id = 8,
                            Email = "Maria.Zahariev@gmail.com",
                            FirstName = "Maria",
                            HireDate = new DateTime(2020, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Zahariev",
                            LocationId = 3,
                            PhoneNumber = "1625380876",
                            Salary = 1534m
                        },
                        new
                        {
                            Id = 9,
                            Email = "Maria.Vladimirov@gmail.com",
                            FirstName = "Maria",
                            HireDate = new DateTime(2020, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Vladimirov",
                            LocationId = 3,
                            PhoneNumber = "4376645777",
                            Salary = 1682m
                        },
                        new
                        {
                            Id = 10,
                            Email = "Alexander.Kolev@gmail.com",
                            FirstName = "Alexander",
                            HireDate = new DateTime(2020, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Kolev",
                            LocationId = 4,
                            PhoneNumber = "5263430484",
                            Salary = 1416m
                        },
                        new
                        {
                            Id = 11,
                            Email = "Boris.Vasilev@gmail.com",
                            FirstName = "Boris",
                            HireDate = new DateTime(2020, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Vasilev",
                            LocationId = 4,
                            PhoneNumber = "5434231100",
                            Salary = 1677m
                        },
                        new
                        {
                            Id = 12,
                            Email = "Petar.Kolev@gmail.com",
                            FirstName = "Petar",
                            HireDate = new DateTime(2020, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Kolev",
                            LocationId = 4,
                            PhoneNumber = "3989778318",
                            Salary = 1595m
                        });
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "бул. Черни връх 47, Младост, 1303",
                            City = "Sofia",
                            Country = "Bulgaria",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Пирин 12, Люлин, 1324",
                            City = "Sofia",
                            Country = "Bulgaria",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Address = "ул. Христо Ботев 23, Център, 1000",
                            City = "Sofia",
                            Country = "Bulgaria",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Address = "ул. Васил Левски 45",
                            City = "Sofia",
                            Country = "Bulgaria",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.LocationMembership", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "MembershipId");

                    b.HasIndex("MembershipId");

                    b.ToTable("LocationMemberships");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Member", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MembershipTierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("MemberId");

                    b.HasIndex("MembershipTierId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.MembershipTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accessibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxSessionsPerMonth")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MembershipTiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accessibility = "address",
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 8,
                            MonthlyPrice = 9.99m,
                            Tier = "Basic"
                        },
                        new
                        {
                            Id = 2,
                            Accessibility = "city",
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 12,
                            MonthlyPrice = 15.99m,
                            Tier = "Advanced"
                        },
                        new
                        {
                            Id = 3,
                            Accessibility = "country",
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 18,
                            MonthlyPrice = 21.99m,
                            Tier = "elite"
                        },
                        new
                        {
                            Id = 4,
                            Accessibility = "any",
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 24,
                            MonthlyPrice = 29.99m,
                            Tier = "Ultimate"
                        });
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MemberId");

                    b.HasIndex("MembershipId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Employee", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.LocationMembership", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Location", "Location")
                        .WithMany("LocationMemberships")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", "Membership")
                        .WithMany("LocationMemberships")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Member", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.MembershipTier", "MembershipTier")
                        .WithMany()
                        .HasForeignKey("MembershipTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Member");

                    b.Navigation("MembershipTier");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Payment", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId");

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.Navigation("Employee");

                    b.Navigation("Member");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Location", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("LocationMemberships");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Member", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", b =>
                {
                    b.Navigation("LocationMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
