// <auto-generated />
using System;
using Fitness_Membership_Tracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness_Membership_Tracker.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260308122802_FixRelationInconsistencyBetweenMemberAndMembership")]
    partial class FixRelationInconsistencyBetweenMemberAndMembership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Member", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MembershipTierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("MembershipTierId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Ivan.Nikolov@gmail.com",
                            FirstName = "Ivan",
                            HireDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Nikolov",
                            LocationId = 1,
                            PhoneNumber = "7876373561",
                            Salary = 1531m
                        },
                        new
                        {
                            Id = 2,
                            Email = "Viktoria.Mihaylov@gmail.com",
                            FirstName = "Viktoria",
                            HireDate = new DateTime(2020, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Mihaylov",
                            LocationId = 1,
                            PhoneNumber = "3595356532",
                            Salary = 1413m
                        },
                        new
                        {
                            Id = 3,
                            Email = "Todor.Angelov@gmail.com",
                            FirstName = "Todor",
                            HireDate = new DateTime(2020, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Angelov",
                            LocationId = 1,
                            PhoneNumber = "3606747674",
                            Salary = 1410m
                        },
                        new
                        {
                            Id = 4,
                            Email = "Katerina.Kovachev@gmail.com",
                            FirstName = "Katerina",
                            HireDate = new DateTime(2020, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Kovachev",
                            LocationId = 2,
                            PhoneNumber = "0593043706",
                            Salary = 1635m
                        },
                        new
                        {
                            Id = 5,
                            Email = "Katerina.Daskalov@gmail.com",
                            FirstName = "Katerina",
                            HireDate = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Daskalov",
                            LocationId = 2,
                            PhoneNumber = "4562632700",
                            Salary = 1669m
                        },
                        new
                        {
                            Id = 6,
                            Email = "Mihail.Zahariev@gmail.com",
                            FirstName = "Mihail",
                            HireDate = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Zahariev",
                            LocationId = 2,
                            PhoneNumber = "1498978746",
                            Salary = 1645m
                        },
                        new
                        {
                            Id = 7,
                            Email = "Ivan.Hristov@gmail.com",
                            FirstName = "Ivan",
                            HireDate = new DateTime(2020, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Hristov",
                            LocationId = 3,
                            PhoneNumber = "5157030913",
                            Salary = 1681m
                        },
                        new
                        {
                            Id = 8,
                            Email = "Hristo.Georgiev@gmail.com",
                            FirstName = "Hristo",
                            HireDate = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Georgiev",
                            LocationId = 3,
                            PhoneNumber = "6848562989",
                            Salary = 1538m
                        },
                        new
                        {
                            Id = 9,
                            Email = "Ivan.Vasilev@gmail.com",
                            FirstName = "Ivan",
                            HireDate = new DateTime(2020, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Vasilev",
                            LocationId = 3,
                            PhoneNumber = "2575297365",
                            Salary = 1654m
                        },
                        new
                        {
                            Id = 10,
                            Email = "Katerina.Georgiev@gmail.com",
                            FirstName = "Katerina",
                            HireDate = new DateTime(2020, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Georgiev",
                            LocationId = 4,
                            PhoneNumber = "6452872148",
                            Salary = 1475m
                        },
                        new
                        {
                            Id = 11,
                            Email = "Nikola.Petrov@gmail.com",
                            FirstName = "Nikola",
                            HireDate = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Petrov",
                            LocationId = 4,
                            PhoneNumber = "3242014495",
                            Salary = 1421m
                        },
                        new
                        {
                            Id = 12,
                            Email = "Svetlana.Angelov@gmail.com",
                            FirstName = "Svetlana",
                            HireDate = new DateTime(2020, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Angelov",
                            LocationId = 4,
                            PhoneNumber = "4675127378",
                            Salary = 1611m
                        });
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "бул. Черни връх 47, Младост, 1303",
                            City = "Sofia",
                            Country = "Bulgaria",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Пирин 12, Люлин, 1324",
                            City = "Sofia",
                            Country = "Bulgaria",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Address = "ул. Христо Ботев 23, Център, 1000",
                            City = "Sofia",
                            Country = "Bulgaria",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Address = "ул. Васил Левски 45",
                            City = "Sofia",
                            Country = "Bulgaria",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.LocationMembership", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "MembershipId");

                    b.HasIndex("MembershipId");

                    b.ToTable("LocationMemberships");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.MembershipTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accessibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxSessionsPerMonth")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MembershipTiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accessibility = "address",
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 8,
                            MonthlyPrice = 9.99m,
                            Tier = "Basic"
                        },
                        new
                        {
                            Id = 2,
                            Accessibility = "city",
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 12,
                            MonthlyPrice = 15.99m,
                            Tier = "Advanced"
                        },
                        new
                        {
                            Id = 3,
                            Accessibility = "country",
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 18,
                            MonthlyPrice = 21.99m,
                            Tier = "elite"
                        },
                        new
                        {
                            Id = 4,
                            Accessibility = "any",
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 24,
                            MonthlyPrice = 29.99m,
                            Tier = "Ultimate"
                        });
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MemberId");

                    b.HasIndex("MembershipId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Member", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.MembershipTier", "MembershipTier")
                        .WithMany()
                        .HasForeignKey("MembershipTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("MembershipTier");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Employee", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.LocationMembership", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Location", "Location")
                        .WithMany("LocationMemberships")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Payment", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId");

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.Navigation("Employee");

                    b.Navigation("Member");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.Data.DataModels.Member", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Location", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("LocationMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
