// <auto-generated />
using System;
using Fitness_Membership_Tracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness_Membership_Tracker.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260321111737_DataModelsForDynamicInteractionBetweenMemberAndTrainer")]
    partial class DataModelsForDynamicInteractionBetweenMemberAndTrainer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Radoslav.Radoslavov@gmail.com",
                            FirstName = "Radoslav",
                            HireDate = new DateTime(2020, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Radoslavov",
                            LocationId = 1,
                            PhoneNumber = "1690599085",
                            Salary = 1676m
                        },
                        new
                        {
                            Id = 2,
                            Email = "Mihail.Todorov@gmail.com",
                            FirstName = "Mihail",
                            HireDate = new DateTime(2020, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Todorov",
                            LocationId = 1,
                            PhoneNumber = "0408046739",
                            Salary = 1639m
                        },
                        new
                        {
                            Id = 3,
                            Email = "Viktoria.Petrov@gmail.com",
                            FirstName = "Viktoria",
                            HireDate = new DateTime(2020, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Petrov",
                            LocationId = 1,
                            PhoneNumber = "2291636215",
                            Salary = 1515m
                        },
                        new
                        {
                            Id = 4,
                            Email = "Hristo.Zahariev@gmail.com",
                            FirstName = "Hristo",
                            HireDate = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Zahariev",
                            LocationId = 2,
                            PhoneNumber = "2216206523",
                            Salary = 1406m
                        },
                        new
                        {
                            Id = 5,
                            Email = "Alexander.Daskalov@gmail.com",
                            FirstName = "Alexander",
                            HireDate = new DateTime(2020, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Daskalov",
                            LocationId = 2,
                            PhoneNumber = "7515980835",
                            Salary = 1495m
                        },
                        new
                        {
                            Id = 6,
                            Email = "Dimitar.Dimitrov@gmail.com",
                            FirstName = "Dimitar",
                            HireDate = new DateTime(2020, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Dimitrov",
                            LocationId = 2,
                            PhoneNumber = "4410796088",
                            Salary = 1557m
                        },
                        new
                        {
                            Id = 7,
                            Email = "Boris.Angelov@gmail.com",
                            FirstName = "Boris",
                            HireDate = new DateTime(2020, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Angelov",
                            LocationId = 3,
                            PhoneNumber = "6850184536",
                            Salary = 1441m
                        },
                        new
                        {
                            Id = 8,
                            Email = "Todor.Zahariev@gmail.com",
                            FirstName = "Todor",
                            HireDate = new DateTime(2020, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Zahariev",
                            LocationId = 3,
                            PhoneNumber = "0604083743",
                            Salary = 1417m
                        },
                        new
                        {
                            Id = 9,
                            Email = "Katerina.Bozhkov@gmail.com",
                            FirstName = "Katerina",
                            HireDate = new DateTime(2020, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Bozhkov",
                            LocationId = 3,
                            PhoneNumber = "8878504377",
                            Salary = 1641m
                        },
                        new
                        {
                            Id = 10,
                            Email = "Mihail.Bozhkov@gmail.com",
                            FirstName = "Mihail",
                            HireDate = new DateTime(2020, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Bozhkov",
                            LocationId = 4,
                            PhoneNumber = "3869889558",
                            Salary = 1549m
                        },
                        new
                        {
                            Id = 11,
                            Email = "Dimitar.Petrov@gmail.com",
                            FirstName = "Dimitar",
                            HireDate = new DateTime(2020, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Petrov",
                            LocationId = 4,
                            PhoneNumber = "2565512649",
                            Salary = 1657m
                        },
                        new
                        {
                            Id = 12,
                            Email = "Alexander.Vasilev@gmail.com",
                            FirstName = "Alexander",
                            HireDate = new DateTime(2020, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Vasilev",
                            LocationId = 4,
                            PhoneNumber = "1766991909",
                            Salary = 1428m
                        });
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "бул. Черни връх 47, Младост, 1303",
                            City = "Sofia",
                            Country = "Bulgaria",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Пирин 12, Люлин, 1324",
                            City = "Sofia",
                            Country = "Bulgaria",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Address = "ул. Христо Ботев 23, Център, 1000",
                            City = "Sofia",
                            Country = "Bulgaria",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Address = "ул. Васил Левски 45",
                            City = "Sofia",
                            Country = "Bulgaria",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.LocationMembership", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "MembershipId");

                    b.HasIndex("MembershipId");

                    b.ToTable("LocationMemberships");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Member", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MembershipTierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("MembershipTierId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.MembershipTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accessibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxSessionsPerMonth")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MembershipTiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accessibility = "address",
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 8,
                            MonthlyPrice = 9.99m,
                            Tier = "Basic"
                        },
                        new
                        {
                            Id = 2,
                            Accessibility = "city",
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 12,
                            MonthlyPrice = 15.99m,
                            Tier = "Advanced"
                        },
                        new
                        {
                            Id = 3,
                            Accessibility = "country",
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 18,
                            MonthlyPrice = 21.99m,
                            Tier = "elite"
                        },
                        new
                        {
                            Id = 4,
                            Accessibility = "any",
                            Description = "Access to gym facilities during staffed hours.",
                            MaxSessionsPerMonth = 24,
                            MonthlyPrice = 29.99m,
                            Tier = "Ultimate"
                        });
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MemberId");

                    b.HasIndex("MembershipId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Maria.Ivanova@gym.com",
                            FirstName = "Maria",
                            HireDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Ivanova",
                            LocationId = 1,
                            PhoneNumber = "0881000001",
                            Salary = 1600m,
                            Specialization = "Yoga"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Georgi.Petrov@gym.com",
                            FirstName = "Georgi",
                            HireDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Petrov",
                            LocationId = 1,
                            PhoneNumber = "0881000002",
                            Salary = 1800m,
                            Specialization = "Personal Training"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Elena.Dimitrova@gym.com",
                            FirstName = "Elena",
                            HireDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Dimitrova",
                            LocationId = 2,
                            PhoneNumber = "0881000003",
                            Salary = 1550m,
                            Specialization = "Pilates"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Nikola.Hristov@gym.com",
                            FirstName = "Nikola",
                            HireDate = new DateTime(2019, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Hristov",
                            LocationId = 2,
                            PhoneNumber = "0881000004",
                            Salary = 1900m,
                            Specialization = "CrossFit"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Viktoria.Stoyanova@gym.com",
                            FirstName = "Viktoria",
                            HireDate = new DateTime(2021, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Stoyanova",
                            LocationId = 3,
                            PhoneNumber = "0881000005",
                            Salary = 1650m,
                            Specialization = "Group Fitness"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Stefan.Vasilev@gym.com",
                            FirstName = "Stefan",
                            HireDate = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Vasilev",
                            LocationId = 3,
                            PhoneNumber = "0881000006",
                            Salary = 1750m,
                            Specialization = "Strength & Conditioning"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Katerina.Nikolova@gym.com",
                            FirstName = "Katerina",
                            HireDate = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Nikolova",
                            LocationId = 4,
                            PhoneNumber = "0881000007",
                            Salary = 1500m,
                            Specialization = "Nutrition"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Hristo.Todorov@gym.com",
                            FirstName = "Hristo",
                            HireDate = new DateTime(2018, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Todorov",
                            LocationId = 4,
                            PhoneNumber = "0881000008",
                            Salary = 2000m,
                            Specialization = "Martial Arts"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Desislava.Angelova@gym.com",
                            FirstName = "Desislava",
                            HireDate = new DateTime(2022, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Angelova",
                            LocationId = 1,
                            PhoneNumber = "0881000009",
                            Salary = 1580m,
                            Specialization = "Cardio"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Alexander.Kolev@gym.com",
                            FirstName = "Alexander",
                            HireDate = new DateTime(2021, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastName = "Kolev",
                            LocationId = 2,
                            PhoneNumber = "0881000010",
                            Salary = 1700m,
                            Specialization = "Swimming"
                        });
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.TrainerCapacity", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerId"));

                    b.Property<int>("MaxTrainees")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId1")
                        .HasColumnType("int");

                    b.HasKey("TrainerId");

                    b.HasIndex("TrainerId1");

                    b.ToTable("TrainerCapacities");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.TrainerSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerSchedules");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.TrainerTrainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerTrainees");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.TrainingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MemberMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<string>("TrainerResponse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainingRequests");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("MemberId");

                    b.HasIndex("MembershipId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkoutLogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutLogId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("WorkoutLogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Employee", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.LocationMembership", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Location", "Location")
                        .WithMany("LocationMemberships")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Member", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Membership", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.MembershipTier", "MembershipTier")
                        .WithMany()
                        .HasForeignKey("MembershipTierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("MembershipTier");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Payment", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId");

                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.Navigation("Employee");

                    b.Navigation("Member");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Trainer", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.TrainerCapacity", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.TrainerSchedule", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.TrainerTrainee", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.TrainingRequest", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Visit", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.Navigation("Location");

                    b.Navigation("Member");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.WorkoutExercise", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.WorkoutLog", "WorkoutLog")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutLog");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.WorkoutLog", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Fitness_Membership_Tracker.Data.DataModels.Member", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Location", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("LocationMemberships");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.Member", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Fitness_Membership_Tracker.Data.DataModels.WorkoutLog", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
